# url to POST to
api_endpoint: http://localhost:3000/data_files/api_create

# specify any parameters to be sent with every POST, these will be added to the multipart POST for all files
# this might be used to provide authentication information if tokens are being used
common_parameters:
  auth_token: 1QpgMVLEkuopbzU4Jwq1

#the name of the file part parameter to send in the multipart post
file_parameter_name: file

# Add one stanza below for each file or file pattern.
# Using a simple string will exactly match a single file
# Using a regular expression will result in all files that match the pattern being uploaded - more below re regex usage
files:
  -
    #directory where the file will be found
    source_directory: /Users/georgina/projects/temp/transferfrom/
    #filename or regex
    file: toa5.dat
    #transfer to path - directory to move files to after successful upload
    transfer_to_directory: /Users/georgina/projects/temp/transferto
    # specify any additional file-specific POST parameters to send with the file, these will be added to the multipart POST
    file_parameters:
      description: some desc
      type: RAW
      experiment_id: 78
  -
    #directory where the file will be found
    source_directory: /Users/georgina/projects/temp/transferfrom/
    # this example uses a regular expression match and will match any file named weather_dddddddd.dat (where d is a digit)
    # standard Ruby regular expressions are supported, as per the example you need to prefix with !ruby/regexp and
    # enclose in forward slashes. Use \A and the start and \z at the end for exact matches, otherwise the below would
    # also match blahweather_dddddddd.dat2 for example
    # TIP: use http://rubular.com/ to construct and test your regex
    file: !ruby/regexp /\Aweather_station_\d{2}_min.dat\z/
    #transfer to path - directory to move files to after successful upload
    transfer_to_directory: /Users/georgina/projects/temp/transferto
    # specify any additional file-specific POST parameters to send with the file, these will be added to the multipart POST
    file_parameters:
      type: UNKNOWN
      experiment_id: 78
      tag_names: 'Photo,Video'
