files:
  -
    path: C:\Campbellsci\LoggerNet
    file: ROS_WS_Table2.dat
    destination: 
      - C:\DC21\data\UploadPending
      - C:\LoggerNet\Backups\YYYYMMDD_HHMMSS
    rotate: monthly
  -
    path: C:\Campbellsci\LoggerNet
    file: ROS_WS_Table05min.dat
    destination: 
      - C:\DC21\data\UploadPending
      - C:\LoggerNet\Backups\YYYYMMDD_HHMMSS
    rotate: weekly
  -
    path: C:\Campbellsci\LoggerNet
    file: ROS_WS_Table05min.dat
    destination: 
      - C:\DC21\data\UploadPending
      - C:\LoggerNet\Backups\YYYYMMDD_HHMMSS
    rotate: weekly
