files:
  -
    path: /tmp/dc21_upload/origin
    file: sample1.dat
    destination: 
      - /tmp/dc21_upload/pending
      - /tmp/dc21_upload/rotate
  -
    path: /tmp/dc21_upload/origin
    file: !ruby/regexp /\Aweather_station_\d{2}_min.dat\z/
    destination: 
      - /tmp/dc21_upload/pending
      - /tmp/dc21_upload/rotate

