api_endpoint: http://localhost:3000/data_files/api_create

common_parameters:
  auth_token: RfmknM43yYnZxtVPfAuH

file_parameter_name: file

files:
  -
    path: placeholder updated by tests
    file_parameters:
      description: some desc
      type: RAW
      experiment_id: 78
  -
    path: placeholder updated by tests
    file_parameters:
      description: another desc
      type: PROCESSED
      experiment_id: invalid
